Repository Kuadrant/authorino, pull requests merged in 2023-09, with the labels that each got.

#426 Add log for when authconfig is de-indexed
  controllers/auth_config_controller.go
  docs/user-guides/sharding.md
Labels: kind/bug, area/doc, participation/good first issue, area/implementation, size/small, target/current

#431 fix: conversion of raw extension fields
  api/v1beta2/auth_config_conversion.go
  api/v1beta2/auth_config_conversion_test.go
Labels: kind/bug, size/small, target/current

#432 fix: missing one-of constraint of top-level when conditions
  install/crd/patches/oneof_in_authconfigs.yaml
  install/manifests.yaml
Labels: kind/bug, area/api, size/small, target/current
